### ISSUE TITLE
AOD & Lock screen editor crash (translation issue) 

### ISSUE THREAD

**Issue by z000026** [pmspr4100/HyperOS-XML-1.0-FRENCH#7]
Hello,

AOD and Lock screen editor menus crash due to translation.

"illegal pattern character "j" at "SimpleDateFormat"

Thanks for your fix.

**Comment by ingbrzy** [comment]
fixed by 
https://github.com/pmspr4100/HyperOS-XML-1.0-FRENCH/commit/643fd87520fa95101d2c80df7e07393a2de37e21
